install:
  # install 7z
  - cinst 7zip.commandline -x86
  
  # fetch deps
  - git clone https://github.com/imazen/gd-win-dependencies.git
  
  # generate test_config.h
  - set TEST_DIR=%CD:\=\\%\\tests
  - echo(#define GDTEST_TOP_DIR "%TEST_DIR%" > tests\test_config.h
  # snprintf fix
  - echo(#define snprintf sprintf_s >> tests\test_config.h


build_script:
  - "\"C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\vcvarsall\""
  - set PLATFORM=86
  - nmake /F appveyor_Makefile.vc /A
  - "\"C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\vcvarsall\" x86_amd64"
  - set PLATFORM=64
  - nmake /F appveyor_Makefile.vc /A


after_build:
  - 7z a libgd-x86.zip .\build_x86\libgd.dll .\build_x86\libgd.lib
  - 7z a libgd-x64.zip .\build_x64\libgd.dll .\build_x64\libgd.lib


test_script:
  - appveyor_run_tests


artifacts:
  - path: libgd-x86.zip
    name: libgd-x86.zip
  - path: libgd-x64.zip
    name: libgd-x64.zip