version: 2.1.1.{build}
shallow_clone: true


environment:
  # settings
  min_build: 1      # if 1 overwrites with_* flags to leave zlib-png-jpeg
  
  with_zlib: 1      # libgd actually won't build without it..
  with_libpng: 1    # needs zlib; removing will break current tests
  with_libjpeg: 1   # removing will break current tests
  with_freetype: 1  
  with_iconv: 0     
  with_tiff: 1      # needs zlib and jpeg
  
  pack_dlls: 1      # will fetch upx
  
  
  static_runtime: 1
  static_gcargs: -DCMAKE_SHARED_LINKER_FLAGS=-static
  static_vcargs:
  #static_vcargs: -DCMAKE_C_FLAGS_RELEASE=/MT
  # ^ don't.
  
  cmake_args: -DCMAKE_LIBRARY_PATH=deps -DCMAKE_INCLUDE_PATH=deps;deps\freetype
  
  
  matrix:
    - build_platform: "x86"
      build_compiler: "msvc"
    
    - build_platform: "x64"
      build_compiler: "msvc"
    
    - build_platform: "x86"
      build_compiler: "mingw"
      build_bindings: 1
    
    - build_platform: "x64"
      build_compiler: "mingw"
      build_bindings: 1



install:
  - curl -k -L -oramdisk_setup.exe -s https://www.softperfect.com/download/freeware/ramdisk_setup.exe
  - dir
  - ramdisk_setup.exe /S /D=C:\ramdisk
  - start /wait C:\ramdisk\ramdiskws /add:letter=X,fs=NTFS,size=512M
  - move .\* X:
  - SET APPVEYOR_BUILD_FOLDER=X:
  - X:
  
  - if [%min_build%]==[1] (
      SET with_zlib=1&&
      SET with_libpng=1&&
      SET with_libjpeg=1&&
      SET with_freetype=0&&
      SET with_iconv=0&&
      SET with_tiff=0)
  
  - ps: if($env:build_platform -eq 'x64') {
          $env:vcvar_arg = 'x86_amd64';
          $env:vc_cm_arg = 'Visual Studio 12 Win64';
          $env:mingw_extra = '-DCMAKE_C_FLAGS=-m64 -DCMAKE_CXX_FLAGS=-m64';
        }
        else {
          $env:vcvar_arg = 'x86';
          $env:vc_cm_arg = 'Visual Studio 12';
          $env:mingw_extra = '';
        }
  
  - ps: 'function prepend($file, $line) { Set-Content (Resolve-Path $file) -value $line,(Get-Content (Resolve-Path $file)) }'
  
  # get common functions
  - git clone https://github.com/imazen/gd-appveyor-helpers
  - ps: . .\gd-appveyor-helpers\appveyor_funcs.ps1
  
  
  # fetch deps
  - mkdir deps
  - ps: if($env:build_bindings -eq 1) { invoke 'git' 'clone https://github.com/imazen/gd-dotnet-bindings-generator.git --depth 1 --branch itanium --single-branch' }
  - ps: if($env:with_zlib -eq 1) {
          invoke 'nuget' "install zlib-$($env:build_compiler)-$($env:build_platform)-master -Source https://ci.appveyor.com/nuget/zlib-94hmpf3q011d";
          move zlib*\* deps -force }
  - ps: if($env:with_libjpeg -eq 1) {
          invoke 'nuget' "install libjpeg-$($env:build_compiler)-$($env:build_platform)-master -Source https://ci.appveyor.com/nuget/libjpeg-turbo-t70qw53csfhj";
          move libjpeg*\* deps -force }
  - ps: if($env:with_libpng -eq 1) {
          invoke 'nuget' "install libpng-$($env:build_compiler)-$($env:build_platform)-master -Source https://ci.appveyor.com/nuget/libpng-i3b6v9aught8";
          move libpng*\* deps -force }
  - ps: if($env:with_freetype -eq 1) {
          invoke 'nuget' "install freetype-$($env:build_compiler)-$($env:build_platform)-master -Source https://ci.appveyor.com/nuget/freetype-vf7bw7v5ec29";
          move freetype*\* deps -force }
  - ps: if($env:with_iconv -eq 1) {
          invoke 'nuget' "install libiconv-$($env:build_compiler)-$($env:build_platform)-master -Source https://ci.appveyor.com/nuget/libiconv-es1y8p1h9c47";
          move libiconv*\* deps -force }
  - ps: if($env:with_tiff -eq 1) {
          invoke 'nuget' "install libtiff-$($env:build_compiler)-$($env:build_platform)-master -Source https://ci.appveyor.com/nuget/libtiff-i3h8tqqy7o7b";
          move libtiff*\* deps -force }
  
  
  # make static names cmake friendly
  - del deps\*.dll*
  - ps: ls deps\*_static.lib | % {move $_ ($_ -replace '_static', '') -force}
  
  
  # get upx (cinst broken; gets dos ver)
  #- if [%pack_dlls%]==[1] cinst upx
  - if [%pack_dlls%]==[1] (
      curl -L -o upx.zip http://upx.sourceforge.net/download/upx391w.zip &&
      7z e upx.zip *.exe -r )
  
  # get mingw-w64 (C:\mingw64)
  - ps: if($env:build_compiler -eq 'mingw' -and $env:build_platform -eq 'x64') {
      invoke 'curl' '-L -o mw64.7z "http://libgd.blob.core.windows.net/mingw/x86_64-4.9.1-release-posix-seh-rt_v3-rev1.7z"';
      invoke '7z' 'x -oC:\ mw64.7z'; }
  
  # get mingw-w64-32bit (C:\mingw32)
  - ps: if($env:build_compiler -eq 'mingw' -and $env:build_platform -eq 'x86' -and $env:build_bindings -eq 1) {
      invoke 'curl' '-L -o mw64-32.7z "http://libgd.blob.core.windows.net/mingw/i686-4.9.1-release-posix-dwarf-rt_v3-rev1.7z"';
      invoke '7z' 'x -oC:\ mw64-32.7z'; }
  
  # sh is breaking mingw builds; remove
  - for %%i in (sh.exe) do @del "%%~$PATH:i"




build_script:
  
  # set env
  
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall" %vcvar_arg%'
  - if [%build_compiler%]==[mingw] if [%build_platform%]==[x86] SET PATH=C:\MinGW\bin;%PATH%
  - if [%build_compiler%]==[mingw] if [%build_platform%]==[x64] SET PATH=C:\mingw64\bin;%PATH%
  
  
  # build msvc
  
  - SET zip=libgd-msvc12-%build_platform%.zip
  - SET cmake_cmd=cmake
      -G "%vc_cm_arg%"
      %cmake_args%
      -DCMAKE_C_FLAGS="/Qvec-report:1"
      -DCMAKE_CXX_FLAGS="/Qvec-report:1"
      -DBUILD_TEST=1
      -DENABLE_PNG=%with_libpng%
      -DENABLE_JPEG=%with_libjpeg%
      -DENABLE_FREETYPE=%with_freetype%
      -DENABLE_ICONV=%with_iconv%
      -DENABLE_TIFF=%with_tiff%
      -Wno-dev
  - if [%static_runtime%]==[1] SET cmake_cmd=%cmake_cmd% %static_vcargs%
  
  - if [%build_compiler%]==[msvc] (
      %cmake_cmd% &&
      msbuild gd.sln /p:Configuration=Release /fl /flp:logfile=msvc%vcvar_arg%.log;verbosity=diagnostic &&
      copy Bin\Release\libgd.dll Bin\Release\libgd_raw.dll &&
      appveyor PushArtifact msvc%vcvar_arg%.log &&
      if [%pack_dlls%]==[1] (
        del Bin\Release\libgd.dll &&
        upx -o Bin\Release\libgd.dll Bin\Release\libgd_raw.dll ))
  
  - ps: if($env:build_compiler -eq 'msvc') {
      invoke '7z' "a $($env:zip) .\Bin\Release\libgd_static.lib .\Bin\Release\libgd.dll .\Bin\Release\libgd.lib";
      Push-AppveyorArtifact $env:zip; }
  
  
  
  # build mingw
  
  - SET zip=libgd-mingw-%build_platform%.zip
  - SET cmake_cmd=cmake
      -G "MinGW Makefiles"
      %mingw_extra%
      %cmake_args%
      -DBUILD_TEST=1
      -DENABLE_PNG=%with_libpng%
      -DENABLE_JPEG=%with_libjpeg%
      -DENABLE_FREETYPE=%with_freetype%
      -DENABLE_ICONV=%with_iconv%
      -DENABLE_TIFF=%with_tiff%
      -Wno-dev
  - if [%static_runtime%]==[1] SET cmake_cmd=%cmake_cmd% %static_gcargs%
  
  - if [%build_compiler%]==[mingw] (
      %cmake_cmd% &&
      mingw32-make &&
      copy Bin\liblibgd.dll Bin\liblibgd_raw.dll &&
      if [%pack_dlls%]==[1] (
        del Bin\liblibgd.dll &&
        upx -o Bin\liblibgd.dll Bin\liblibgd_raw.dll ))
  
  - ps: if($env:build_compiler -eq 'mingw') {
      invoke '7z' "a $($env:zip) .\Bin\liblibgd.dll .\Bin\liblibgd.dll.a .\Bin\liblibgd.a";
      Push-AppveyorArtifact $env:zip; }
  
  
  
  # build bindings
  
  - ps: if($env:with_tiff -eq 0 -and $env:build_bindings -eq 1) {
      prepend 'gd-dotnet-bindings-generator\LibGD.CLI\LibGDExtensions.cs' '#define NO_TIFF';
      $env:test_defs += 'NO_TIFF;' }
  - ps: if($env:with_freetype -eq 0 -and $env:build_bindings -eq 1) {
      prepend 'gd-dotnet-bindings-generator\LibGD.CLI\LibGDExtensions.cs' '#define NO_FREETYPE';
      $env:test_defs += 'NO_FREETYPE;' }
  
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall"'
  - if [%build_bindings%]==[1] if [%build_compiler%]==[mingw] (
      cd gd-dotnet-bindings-generator &&
      msbuild LibGD.CLI\LibGD.CLI.csproj /p:Configuration=Debug /p:Platform=AnyCPU /v:m &&
      copy ..\Bin\liblibgd_raw.dll LibGD.CLI\bin\Debug\liblibgd.dll &&
      cd LibGD.CLI\bin\Debug &&
      (if [%build_platform%]==[x86] (LibGD.CLI.exe %APPVEYOR_BUILD_FOLDER%\src C:\mingw32\bin\mingw32-make.exe liblibgd.dll)
      else if [%build_platform%]==[x64] (LibGD.CLI.exe %APPVEYOR_BUILD_FOLDER%\src C:\mingw64\bin\mingw32-make.exe liblibgd.dll)) &&
      cd ..\..\.. &&
      msbuild LibGD.Tests\LibGD.Tests.csproj /p:Configuration=Debug /p:Platform=AnyCPU /p:DefineConstants="%test_defs%" /v:m &&
      cd..)
  
  - ps: if($env:build_bindings -eq 1 -and $env:build_compiler -eq 'mingw') {
      invoke '7z' "a LibGDSharp-$($env:build_platform).zip
        .\Bin\liblibgd.dll
        .\gd-dotnet-bindings-generator\LibGD.CLI\bin\Debug\_iobuf.cs
        .\gd-dotnet-bindings-generator\LibGD.CLI\bin\Debug\LibGD.cs
        .\gd-dotnet-bindings-generator\LibGD.CLI\bin\Debug\LibGDExtensions.cs
        .\gd-dotnet-bindings-generator\LibGD.CLI\bin\Debug\LibGDSharp.dll";
      Push-AppveyorArtifact "LibGDSharp-$($env:build_platform).zip"; }




test_script:
  - SET fail=0
  - ctest -C Release || SET fail=1 & ver > nul
  - ps: Push-Ctest-Results '.'
  - ps: Push-AppveyorArtifact Testing\Temporary\LastTest.log
  - exit %fail%
  
  - if [%build_bindings%]==[1] if [%build_compiler%]==[mingw] (
      copy Bin\liblibgd.dll gd-dotnet-bindings-generator\LibGD.Tests\bin\Debug\liblibgd.dll &&
      (if [%build_platform%]==[x86] (nunit-console-x86 gd-dotnet-bindings-generator\LibGD.Tests\bin\Debug\LibGD.Tests.dll)
      else if [%build_platform%]==[x64] (nunit-console gd-dotnet-bindings-generator\LibGD.Tests\bin\Debug\LibGD.Tests.dll)) &&
      appveyor PushArtifact TestResult.xml )
