homepage: "https://libgd.org"
language: c++
primary_contact: "security@libgd.org"
auto_ccs:
  - vapier@gmail.com
  - tim@tim-smith.us
  - cmbecker69@gmx.de
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
