name: Example CMake

on:
  push:
    branches: [ 'features/mingw-ci' ]
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        fail-fast: false
        include:
          - { sys: mingw32, env: i686 }
          - { sys: mingw64, env: x86_64 }
          - { sys: clang64, env: clang-x86_64 } # Experimental!
    name: ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2'
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          git
          make
          mingw-w64-${{matrix.env}}-toolchain
          mingw-w64-${{matrix.env}}-cmake
          mingw-w64-${{matrix.env}}-ninja
    - name: Build
      run: |
        ls -al
        pwd